platform: linux
image_resource:
  type: docker-image
  source:
    repository: qiime2/linux-worker
    version: latest

params:
  PATH: /opt/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

inputs:
  - name: iab-env
  - name: biab-provisioning
  - name: iab-source
  - name: build-iab

outputs:
  - name: built-s3

run:
  path: biab-provisioning/bin/build-s3.sh
