platform: linux
image_resource:
  type: docker-image
  source:
    repository: qiime2/linux-worker
    version: latest

inputs:
  - name: biab-provisioning
  - name: iab-source
  - name: updated-built-iab

outputs:
  - name: final-built-iab

run:
  path: biab-provisioning/bin/copy-env.sh
