platform: linux
image_resource:
  type: docker-image
  source:
    repository: qiime2/linux-worker
    version: latest

inputs:
  - name: build-iab
  - name: built-s3

run:
  path: biab-provisioning/bin/upload-s3.sh
